# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19faa6dfbd0d63215c449a5b836c78c4131a60848343579b5771a8c7642df15f96c195ccb4b3274d9f09f30a6a58c08e16e581d8969a9bef0cd9aabd5fab62aa

test:
  secret_key_base: ca97e61ac7c1d965df1faf2a9736dcb4f5528b5901f03c2d5fd27b6e71bba0d6869d96f925ec98e8f3058e4113503e3345d0235a18afc4db77c97d291e0019dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
